version: "3.9"

services:
  postgres:
    container_name: pg_gogag
    image: postgres:16.3-alpine3.19
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=gogag
