version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      HOST: ${HOST}
    depends_on:
      - db

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    command: ["npm", "run", "build"]
    volumes:
      - .:/app

  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/db.sql
